name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        version: 2.2.108
    - name: Build with dotnet
      run: dotnet publish -c Release
    - name: Deploy to Azure
      uses: azure/appservice-actions/webapp@master
      with: 
        app-name: awesome-bookmarks
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: /home/runner/work/awesome-bookmarks/awesome-bookmarks/src/bookmarks/bin/Release/netcoreapp2.2/publish/
