name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        version: 2.2.108
    - name: Devskim
      uses: anuraj/devskim-action@0.3
    - name: Build with dotnet
      run: dotnet publish -c Release
